[package]
name = "dataclass_to_diagram"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.11.0"
handlebars = { version = "4.4", features = ["dir_source"] }

[dependencies.derive_more]
version = "0.99.17"
default-features = false
features = ["display"]
