[package]
name = "dataclass_to_diagram"
version = "0.1.0"
edition = "2021"

[dependencies]
# derive_more = "0.99.17"
enum-iterator = "1.4.1"

[dependencies.derive_more]
version = "0.99.17"
default-features = false
features = ["display"]
