@startuml

state Start <<start>>
state "NotShooting" as NotShooting {
    state NotShootingStart <<start>>
    state "Idle" as NotShootingIdle
    state "Configuring" as NotShootingConfiguring {
        state NotShootingConfiguringStart <<start>>
        state "NewValueSelection" as NotShootingConfiguringNewValueSelection
        state "NewValuePreview" as NotShootingConfiguringNewValuePreview {
            state "State1" as NotShootingConfiguringNewValuePreviewState1
            state "State2" as NotShootingConfiguringNewValuePreviewState2
        }
    }
}

Start --> NotShooting : 0
NotShootingStart --> NotShootingIdle : 1
NotShootingIdle --> NotShootingConfiguring : 2
NotShootingConfiguring --> NotShootingIdle : 3
NotShootingConfiguringStart --> NotShootingConfiguringNewValueSelection : 4
NotShootingConfiguringNewValueSelection --> NotShootingConfiguringNewValuePreview : 5
NotShootingConfiguringNewValuePreview --> NotShootingConfiguringNewValueSelection : 6
NotShootingConfiguringNewValuePreview --> NotShootingConfiguringNewValueSelection : 7
NotShootingConfiguringNewValuePreviewState1 --> NotShootingConfiguringNewValuePreviewState2 : 8

json Transitions {
    "0": "",
    "1": "",
    "2": "EvConfig",
    "3": "EvConfig",
    "4": "",
    "5": "EvNewValue",
    "6": "EvNewValueRejected",
    "7": "EvNewValueSaved",
    "8": "EvNewValueSaved"
}

@enduml