@startuml

state Start <<start>>
state "State1" as State1
state "State2" as State2
state "State3" as State3 {
    state State3Start <<start>>
    state "Accumulate Enough Data\nLong State Name" as State3Accum
    State3Accum : Just a test
    state "PrecessData" as State3ProcessData
}
state End <<end>>

Start --> State1 : 0
State1 --> State2 : 1
State1 --> End : 2
State2 --> State3 : 3
State2 --> End : 4
State3 --> End : 5
State3 --> End : 6
State3 --> State3 : 7
State3Start --> State3Accum : 8
State3Accum --> State3Accum : 9
State3Accum --> State3ProcessData : 10

json Transitions {
    "0": "",
    "1": "Succeeded",
    "2": "Aborted",
    "3": "Succeeded",
    "4": "Aborted",
    "5": "Succeeded / Save Result",
    "6": "Aborted",
    "7": "Failed",
    "8": "",
    "9": "New Data",
    "10": "Enough Data"
}

@enduml