@startuml

hide empty description

state Start <<start>>
state "State1" as State1
State1 : this is string
State1 : this is another string
state "State2" as State2
state End <<end>>

Start --> State1
State1 --> State2
State1 --> End
State2 --> End

@enduml