@startuml

state Start <<start>>
state "NotShooting" as NotShooting {
    state NotShootingStart <<start>>
    state "Idle" as NotShootingIdle
    state "Configuring" as NotShootingConfiguring {
        state NotShootingConfiguringStart <<start>>
        state "NewValueSelection" as NotShootingConfiguringNewValueSelection
        state "NewValuePreview" as NotShootingConfiguringNewValuePreview {
            state "State1" as NotShootingConfiguringNewValuePreviewState1
            state "State2" as NotShootingConfiguringNewValuePreviewState2
        }
    }
}

Start --> NotShooting
NotShootingStart --> NotShootingIdle
NotShootingIdle --> NotShootingConfiguring : EvConfig
NotShootingConfiguring --> NotShootingIdle : EvConfig
NotShootingConfiguringStart --> NotShootingConfiguringNewValueSelection
NotShootingConfiguringNewValueSelection --> NotShootingConfiguringNewValuePreview : EvNewValue
NotShootingConfiguringNewValuePreview --> NotShootingConfiguringNewValueSelection : EvNewValueRejected
NotShootingConfiguringNewValuePreview --> NotShootingConfiguringNewValueSelection : EvNewValueSaved
NotShootingConfiguringNewValuePreviewState1 --> NotShootingConfiguringNewValuePreviewState2 : EvNewValueSaved

@enduml